version: '3.1'

services:

  db:
    container_name: mysqldb
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: main
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/datadump.sql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - db    
    ports:
      - 9091:8080
  
  app:
    container_name: test-app
    image: pabloalvez98/php-app:v1
    restart: always
    depends_on:
      - db    
    ports:
      - 8081:80 
    environment:
      DB_HOST: mysqldb
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: main
  
  ngrok:
    container_name: ngrok
    image: ngrok/ngrok
    restart: always
    depends_on:
      - app   
    command: http test-app:80 --authtoken=22FPkGNszGxyKEYX47LbjFLRbAs_3qiQFwV4yD2rhGxTdYfLE   

  