kind: Service
apiVersion: v1
metadata:
  name:  web-app-service
  labels:
    application: web-app
spec:
  selector:
    application: web-app
  type:  ClusterIP
  ports:
  - name:  web-app-external-port
    port:  8080
    targetPort: 80
    