apiVersion: v1
kind: Secret
metadata:
  name: web-app-secret
  labels:
    application: web-app
type: Opaque
data:
    DB_USER: dXNlcgo=
    DB_PASSWORD: cGFzc3dvcmQK
    DB_HOST: bXlzcWwtc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsCg==
    DB_DATABASE: bWFpbgo=