apiVersion: v1
kind: Secret
metadata:
  name: web-app-secret
  labels:
    application: web-app
kubernetes.io/basic-auth:
stringData:
  DB_USER: user
  DB_PASSWORD: password
  DB_HOST: mysql-service
  DB_DATABASE: main