apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app-claim
  labels:
    application: web-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi