apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-app-volume
  labels:
    type: local
    application: web-app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/web-app-img"