apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
   matchLabels:
    application: mysql
  replicas: 1
  template:
    metadata:
      labels:
        application: mysql
    spec:
      containers:
      - name: mysqldb
        image: mysql:5.6
        ports:
          - containerPort: 3306
        envFrom:
          - secretRef:
              name: mysql-secret
        volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldb
            - mountPath: /docker-entrypoint-initdb.d/
              name : mysql-dump
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: mysql-claim
        - name: mysql-dump
          configMap:
             name: mysql-configmap