kind: Service
apiVersion: v1
metadata:
  name:  mysql-service
  labels:
    application: mysql
spec:
  selector:
    application: mysql
  type:  NodePort
  ports:
  - name:  mysql-internal-port
    port:  3306