apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    application: mysql
kubernetes.io/basic-auth:
stringData:
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: main