apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    application: mysql
type: Opaque
data:
    MYSQL_USER: dXNlcgo=
    MYSQL_PASSWORD: cGFzc3dvcmQK
    MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkCg==
    MYSQL_DATABASE: bWFpbgo=